[package]
name = "genkei"
version = "0.1.3"
edition = "2021"
license = "MIT"

[dependencies]

[features]
default = ["html", "style"]
html = []
style = []
deprecated = ["html"]
macros = ["html"]
htmx = ["html"]
all = [
    "html",
    "style",
    "deprecated",
    "macros",
    "htmx",
]
