[package]
name = "genkei-tests"
version = "0.1.3"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genkei = { path = "../genkei", features = ["all"] }